### ISSUE TITLE
Repo description is wrong

### ISSUE THREAD

**Issue by fredfb** [Deevad/peppercarrot_ep08_translation#10]
The repo's description reads:
Source folder with SVG to crowdsource translation of the webcomic Pepper and Carrot episode 6: The potion challenge

it should be:
Source folder with SVG to crowdsource translation of the webcomic Pepper and Carrot episode 8: Pepper's Birthday Party

**Comment by Deevad** [comment]
Oops, that is what happens when I abuse copy/paste in last production week at 2:00 am  xD 
Thanks for the report, and I'll fix it right now :)
