### ISSUE TITLE
FIx correction

### ISSUE THREAD

**Issue by mrk1989** [Deevad/peppercarrot_ep08_translation#6]
In this image: http://www.peppercarrot.com/0_sources/2015-06-28_ep08_Birthday-Party/low-res/en_Pepper-and-Carrot_by-David-Revoy_E08P07.jpg 
There are two error on (same) words "poi" .
"id="flowPara4735">Anche tu poi fare una donazione </flowPara>" line 139
"id="flowPara3318">Tu poi modificare, condividere, vendere etc. ...</flowPara>" line 193
Fonts: https://github.com/Deevad/peppercarrot_ep08_translation/blob/master/it/Pepper-and-Carrot_by-David-Revoy_E08P07.svg?short_path=6b55141
Please replace "poi" with "puoi".
Also translate of google suggest same corrections. https://translate.google.it/#it/fr/poi%20fare%20questo
This is my first issue on github :P

**Comment by Deevad** [comment]
Thanks @mrk1989 for the report. 

@cgand Hey , can you look at this bug report ?

**Comment by cgand** [comment]
Fixed, sorry for the typo,
Thank,
C.

**Comment by Deevad** [comment]
Thank you @cgand and @mrk1989  !
I'll update the page online tomorrow morning :-)
